# API Configuration - Sales Analytics API

api:
  name: "Sales Analytics API"
  version: "1.0.0"
  environment: "production"
  
  endpoints:
    base_url: "https://api.shopflow.com/v1"
    health_check: "/health"
    query: "/query"
    fields: "/fields"
  
  authentication:
    type: "api_key"
    header_name: "X-API-Key"
    key_format: "sk_live_[32_characters]"
    rotation_days: 90
  
  rate_limiting:
    requests_per_hour: 1000
    requests_per_minute: 100
    burst_limit: 50
    window_size: 3600
  
  timeouts:
    request_timeout: 30
    connection_timeout: 10
    read_timeout: 30
  
  retry_policy:
    max_retries: 3
    backoff_strategy: "exponential"
    initial_delay: 1000
    max_delay: 10000

data_sources:
  primary:
    type: "postgresql"
    host: "analytics-db.shopflow.com"
    port: 5432
    database: "sales_analytics"
    schema: "public"
    connection_pool:
      min_connections: 5
      max_connections: 50
      idle_timeout: 300
  
  cache:
    type: "redis"
    host: "cache.shopflow.com"
    port: 6379
    database: 0
    ttl_default: 900
    max_memory: "2GB"

query_engine:
  max_records: 10000
  max_execution_time: 30
  max_memory_usage: "2GB"
  default_limit: 1000
  max_filters: 20
  max_aggregates: 10
  
  optimization:
    enable_query_cache: true
    cache_ttl: 900
    enable_query_rewriting: true
    enable_index_hints: true
  
  monitoring:
    log_slow_queries: true
    slow_query_threshold: 5
    log_all_queries: false
    metrics_collection: true

security:
  encryption:
    data_at_rest: "AES-256"
    data_in_transit: "TLS-1.3"
    key_rotation_days: 90
  
  access_control:
    enable_rbac: true
    default_role: "viewer"
    admin_roles: ["admin", "data_analyst"]
  
  audit:
    log_all_requests: true
    log_sensitive_data: false
    retention_days: 730
    export_format: "json"

logging:
  level: "INFO"
  format: "json"
  output: "stdout"
  
  loggers:
    query_engine: "DEBUG"
    security: "WARN"
    performance: "INFO"
    errors: "ERROR"
  
  structured_fields:
    - "request_id"
    - "user_id"
    - "query_type"
    - "execution_time"
    - "records_returned"

monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"
    format: "prometheus"
    collection_interval: 30
  
  health_checks:
    database: true
    cache: true
    external_apis: false
    interval: 30
  
  alerting:
    enabled: true
    channels:
      - "slack"
      - "email"
      - "pagerduty"
    
    thresholds:
      error_rate: 0.05
      response_time: 2000
      cpu_usage: 0.8
      memory_usage: 0.9

features:
  query_features:
    filtering: true
    aggregation: true
    sorting: true
    pagination: true
    field_selection: true
  
  advanced_features:
    custom_functions: false
    window_functions: false
    subqueries: false
    joins: false
    unions: false
  
  export_formats:
    - "json"
    - "csv"
    - "xlsx"
  
  integrations:
    webhooks: false
    streaming: false
    batch_processing: false

performance:
  connection_pooling: true
  query_caching: true
  result_compression: true
  parallel_processing: true
  
  optimization:
    index_usage: true
    query_rewriting: true
    materialized_views: false
    partitioning: true

compliance:
  data_retention:
    customer_data: 2555  # 7 years in days
    transaction_data: 1095  # 3 years in days
    audit_logs: 730  # 2 years in days
  
  privacy:
    gdpr_compliance: true
    data_anonymization: true
    right_to_deletion: true
    data_portability: true
  
  security_standards:
    pci_dss: true
    sox_compliance: true
    iso_27001: true
    soc2_type2: true
