receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  file:
    path: /var/log/otel-collector.json
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
    metrics:
      receivers: [otlp]
      exporters: [file]
    logs:
      receivers: [otlp]
      exporters: [file]
