server:
  port: 8080

mcp:
  http:
    path: /mcp

providers:
  openai:
    apiKey: ${OPENAI_API_KEY:}
    baseUrl: ${OPENAI_BASE_URL:}
  gemini:
    apiKey: ${GEMINI_API_KEY:}
    endpoint: ${GEMINI_ENDPOINT:}
  anthropic:
    apiKey: ${ANTHROPIC_API_KEY:}
    baseUrl: ${ANTHROPIC_BASE_URL:}

typescript:
  runtimeUrl: ${TS_RUNTIME_URL:http://localhost:7070}

foundation:
  dir: ${FOUNDATION_DIR:/var/foundation}

guardrails:
  strict: ${GUARDRAILS_STRICT:true}

kb:
  autoContext:
    enabled: true
    topK: 4

otel:
  service:
    name: mcpagent
